project:
  type: book
  output-dir: docs

book:
  title: "Python for Data Science in Finance"
  author: "Pritam Dalal"
  chapters:
    - index.qmd
    - chapters/01_jumpstart/jumpstart.ipynb
    - part: parts/01_part_basic_data_wrangling/part_basic_data_wrangling.ipynb
      chapters:
      - chapters/02_dataframe_basics/dataframe_basics.ipynb
      - chapters/03_index_slice/index_slice.ipynb
      - chapters/04_query/query.ipynb
      - chapters/05_functions_apply/functions_apply.ipynb
      - chapters/06_merge/merge.ipynb
      - chapters/07_groupby_aggregation_part_1/groupby_aggregation_part_1.ipynb
      - chapters/08_groupby_aggregation_part_2/groupby_aggregation_part_2.ipynb
    - part: parts/02_part_visualization/part_visualization.ipynb
      chapters:
      - chapters/09_pandas_line_graphs/pandas_line_graphs.ipynb
      - chapters/10_pandas_bar_charts/pandas_bar_charts.ipynb
      - chapters/11_pandas_scatter_plots/pandas_scatter_plots.ipynb
      - chapters/12_seaborn/seaborn.ipynb
      - chapters/13_bokeh_basic/bokeh_basic.ipynb
      - chapters/14_bokeh_advanced/bokeh_advanced.ipynb
    - part: parts/03_data_analysis/data_analysis.ipynb
      chapters:
      - chapters/15a_option_replication/option_replication.ipynb
      - chapters/15b_asset_allocation/asset_allocation.ipynb
      - chapters/16_trend_following/trend_following.ipynb
      - chapters/17_regression_mutual_fund/regression_mutual_fund.ipynb
      - chapters/18_close_to_close/close_to_close.ipynb
      - chapters/19_garch/garch.ipynb
      - chapters/20_feed_grains_database/feed_grains_database.ipynb
    - part: parts/04_classical_machine_learning/classical_machine_learning.ipynb
      chapters:
      - chapters/21_simple_linear_regression/simple_linear_regression.ipynb
      - chapters/22_categorical_linear_regression/categorical_linear_regression.ipynb
      - chapters/23_ridge_lasso_regression/ridge_lasso_regression.ipynb
      - chapters/24_k_nearest_neighbors_cross_validation/k_nearest_neighbors_cross_validation.ipynb
      - chapters/25_stock_prediction/stock_prediction.ipynb
      - chapters/26a_pca/pca.ipynb
      - chapters/26b_principal_components_regression/principal_components_regression.ipynb
      - chapters/26c_principal_components_logistic_regression/principal_components_logistic_regression.ipynb
      - chapters/27_k_means_clustering/k_means_clustering.ipynb
      - chapters/28_pca_visualization/pca_visualization.ipynb
      - chapters/29_student_loan_overfitting/student_loan_overfitting.ipynb
      - chapters/30_student_loan_alternative_metric/student_loan_alternative_metric.ipynb
      - chapters/31_student_loan_hyperparameter_tuning/student_loan_hyperparameter_tuning.ipynb
      - chapters/32_student_loan_xgboost/student_loan_xgboost.ipynb
      - chapters/33_option_volume_introduction/option_volume_introduction.ipynb
      - chapters/34_option_volume_feature_selection/option_volume_feature_selection.ipynb
      - chapters/35_option_volume_xgboost/option_volume_xgboost.ipynb
    - part: parts/05_neural_networks/neural_networks.ipynb
      chapters:
      - chapters/36a_mnist_digit_recognition/mnist_digit_recognition.ipynb
      - chapters/36b_imdb_classification/imdb_classification.ipynb
      - chapters/36c_reuters_classification/reuters_classification.ipynb
      - chapters/36d_boston_house_price_regression/boston_house_price_regression.ipynb
      - chapters/37_student_loan_neural_network/student_loan_neural_network.ipynb
      - chapters/38_exchange_rate/exchange_rate.ipynb
      - chapters/39_stock_prediction_neural_network/stock_prediction_neural_network.ipynb
      - chapters/40_numerai/numerai.ipynb
      - chapters/41_exchange_rate_rnn/exchange_rate_rnn.ipynb
    - part: parts/06_natural_language_processing/natural_language_processing.ipynb
      chapters:
      - chapters/41a_spacy_introduction/spacy_introduction.ipynb
      - chapters/41b_nltk_introduction/nltk_introduction.ipynb
      - chapters/41c_vectorizing_text/vectorizing_text.ipynb
      - chapters/41d_sentiment_analysis_stock_headlines/sentiment_analysis_stock_headlines.ipynb
    - part: parts/07_miscellaneous/miscellaneous.ipynb
      chapters:
      - chapters/42_virtual_environments/virtual_environments.ipynb
      - chapters/43_pipelines_pickles/pipelines_pickles.ipynb
      - chapters/44_columntransformers/columntransformers.ipynb
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo