project:
  type: book
  output-dir: docs

book:
  title: "Python for Data Analysis in Finance"
  author: "Pritam Dalal"
  chapters:
    - index.qmd
    - chapters/01_jumpstart/jumpstart.ipynb
    - chapters/02_dataframe_basics/dataframe_basics.ipynb
    - chapters/03_index_slice/index_slice.ipynb
    - chapters/04_query/query.ipynb
    - chapters/05_functions_apply/functions_apply.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



